name: C++ checks
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            config: Debug
            sanitizers: ON
          - os: macos-latest
            config: Release
            sanitizers: OFF
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DORBIT_SANITIZERS=${{ matrix.sanitizers }}
      - name: Build
        run: cmake --build build --parallel 3
      - name: Test
        run: ctest --test-dir build --output-on-failure
